apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginxdeploymentlabel
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginxpodlabel
  template:
    metadata:
      labels:
        name: nginxpodlabel
    spec:
      containers:
      - name: nginxcontainername
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: nginxpodlabel

