---



- hosts: all
  gather_facts: yes
  tasks:
    - name: common tasks
      include_role:
        name: common
    - name: install docker 
      include_role: 
        name: docker
    - name: install crio
      include_role:
        name: crio
    - name: setup k8s cluster 
      include_role: 
        name: k8s
