apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    nodePort: 32123
  selector:
    app: guestbook
    tier: frontend

