apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginxpodlabel
  template:
    metadata:
      labels:
        name: nginxpodlabel
    spec:
      containers:
      - image: nginx:latest
        command: ["/bin/sh"]
        args: ["-c", "do echo echo $(date -u) 'Hi I am from Sidecar container 1' >> /var/log/index.html; sleep 5;done"]
        name: webapp1
        port:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    name: nginxpodlabel

